# Generated by Django 5.1.5 on 2025-02-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
