# Generated by Django 5.1.5 on 2025-02-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_contato_options_alter_produto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Blog'},
        ),
    ]
