# Generated by Django 5.1.5 on 2025-03-05 20:16

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_postagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias de Calçados'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategoria', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
