# Generated by Django 5.1.5 on 2025-03-12 16:50

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('codigo_hex', models.CharField(max_length=7)),
                ('imagem', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='cores_variacao/')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='produto.variacao')),
            ],
            options={
                'verbose_name': 'Cor da Variação',
                'verbose_name_plural': 'Cores das Variações',
            },
        ),
    ]
