# Generated by Django 5.1.5 on 2025-03-12 17:09

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_corvariacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('codigo_hex', models.CharField(max_length=7)),
                ('imagem', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='cores_produtos/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.DeleteModel(
            name='CorVariacao',
        ),
    ]
