# Generated by Django 5.1.5 on 2025-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_cor_delete_corvariacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='codigo_hex',
            field=models.CharField(choices=[('#0000FF', 'Azul'), ('#FF0000', 'Vermelho'), ('#00FF00', 'Verde'), ('#FFFF00', 'Amarelo'), ('#FFFFFF', 'Branco'), ('#000000', 'Preto'), ('#FFA500', 'Laranja'), ('#800080', 'Roxo'), ('#FFC0CB', 'Rosa'), ('#808080', 'Cinza'), ('#FFD700', 'Dourado')], default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
