# Generated by Django 5.1.5 on 2025-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_cor_options_remove_cor_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='codigo_hex',
            field=models.CharField(choices=[('#000000', 'Preto'), ('#FFFFFF', 'Branco'), ('#FF0000', 'Vermelho'), ('#0000FF', 'Azul'), ('#008000', 'Verde'), ('#FFFF00', 'Amarelo'), ('#FFA500', 'Laranja'), ('#800080', 'Roxo'), ('#A52A2A', 'Marrom'), ('#C0C0C0', 'Cinza')], max_length=7, verbose_name='Código Hex da Cor'),
        ),
    ]
