# Generated by Django 5.1.5 on 2025-03-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_cor_codigo_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_cor_padrao', to='produto.cor', verbose_name='Cor Padrão'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_padrao',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/imagens_padrao/', verbose_name='Imagem Padrão'),
        ),
        migrations.AlterField(
            model_name='cor',
            name='codigo_hex',
            field=models.CharField(choices=[('#000000', 'Preto'), ('#FFFFFF', 'Branco'), ('#FF0000', 'Vermelho'), ('#0000FF', 'Azul'), ('#008000', 'Verde'), ('#FFFF00', 'Amarelo'), ('#FFA500', 'Laranja'), ('#800080', 'Roxo'), ('#A52A2A', 'Marrom'), ('#C0C0C0', 'Cinza'), ('#FFC0CB', 'Rosa'), ('#FFD700', 'Dourado'), ('#00FFFF', 'Ciano'), ('#808080', 'Grafite'), ('#8B4513', 'Marrom Escuro'), ('#FF4500', 'Vermelho Alaranjado'), ('#4B0082', 'Índigo'), ('#00FF00', 'Verde Limão'), ('#FF1493', 'Rosa Choque'), ('#000080', 'Azul Marinho')], max_length=7, verbose_name='Código Hex da Cor'),
        ),
    ]
