# Generated by Django 5.1.5 on 2025-03-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produto_cor_padrao_produto_imagem_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor_padrao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem_padrao',
        ),
    ]
