# Generated by Django 5.1.5 on 2025-03-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_alter_produto_options_produto_cor_padrao_codigo_hex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produtos', 'verbose_name_plural': 'Produtos da Loja'},
        ),
    ]
