# Generated by Django 5.1.5 on 2025-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_alter_produto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='codigo_hex',
            field=models.CharField(choices=[('#000000', 'Preto'), ('#FFFFFF', 'Branco'), ('#FF0000', 'Vermelho'), ('#0000FF', 'Azul'), ('#008000', 'Verde'), ('#FFFF00', 'Amarelo'), ('#FFA500', 'Laranja'), ('#800080', 'Roxo'), ('#A52A2A', 'Marrom'), ('#C0C0C0', 'Cinza'), ('#FFC0CB', 'Rosa'), ('#FFD700', 'Dourado'), ('#00FFFF', 'Ciano'), ('#808080', 'Grafite'), ('#8B4513', 'Marrom Escuro'), ('#FF4500', 'Vermelho Alaranjado'), ('#4B0082', 'Índigo'), ('#00FF00', 'Verde Limão'), ('#FF1493', 'Rosa Choque'), ('#000080', 'Azul Marinho'), ('#B22222', 'Vermelho Tijolo'), ('#2E8B57', 'Verde Musgo'), ('#4682B4', 'Azul Aço'), ('#D2691E', 'Chocolate'), ('#BC8F8F', 'Rosa Antigo'), ('#1E90FF', 'Azul Céu'), ('#FF6347', 'Tomate'), ('#556B2F', 'Verde Militar'), ('#FA8072', 'Salmão'), ('#DAA520', 'Mostarda'), ('#F5F5DC', 'Bege'), ('#696969', 'Cinza Escuro'), ('#483D8B', 'Azul Royal'), ('#E6E6FA', 'Lavanda'), ('#FFDAB9', 'Pêssego'), ('#CD853F', 'Camurça'), ('#191970', 'Azul Meia-noite'), ('#8B0000', 'Vermelho Escuro'), ('#F4A460', 'Sépia')], max_length=7, verbose_name='Código Hex da Cor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cor_padrao_codigo_hex',
            field=models.CharField(choices=[('#000000', 'Preto'), ('#FFFFFF', 'Branco'), ('#FF0000', 'Vermelho'), ('#0000FF', 'Azul'), ('#008000', 'Verde'), ('#FFFF00', 'Amarelo'), ('#FFA500', 'Laranja'), ('#800080', 'Roxo'), ('#A52A2A', 'Marrom'), ('#C0C0C0', 'Cinza'), ('#FFC0CB', 'Rosa'), ('#FFD700', 'Dourado'), ('#00FFFF', 'Ciano'), ('#808080', 'Grafite'), ('#8B4513', 'Marrom Escuro'), ('#FF4500', 'Vermelho Alaranjado'), ('#4B0082', 'Índigo'), ('#00FF00', 'Verde Limão'), ('#FF1493', 'Rosa Choque'), ('#000080', 'Azul Marinho'), ('#B22222', 'Vermelho Tijolo'), ('#2E8B57', 'Verde Musgo'), ('#4682B4', 'Azul Aço'), ('#D2691E', 'Chocolate'), ('#BC8F8F', 'Rosa Antigo'), ('#1E90FF', 'Azul Céu'), ('#FF6347', 'Tomate'), ('#556B2F', 'Verde Militar'), ('#FA8072', 'Salmão'), ('#DAA520', 'Mostarda'), ('#F5F5DC', 'Bege'), ('#696969', 'Cinza Escuro'), ('#483D8B', 'Azul Royal'), ('#E6E6FA', 'Lavanda'), ('#FFDAB9', 'Pêssego'), ('#CD853F', 'Camurça'), ('#191970', 'Azul Meia-noite'), ('#8B0000', 'Vermelho Escuro'), ('#F4A460', 'Sépia')], default='#000000', max_length=7, verbose_name='Código Hex da Cor Padrão'),
        ),
    ]
