# Generated by Django 5.1.5 on 2025-03-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
