# Generated by Django 5.1.5 on 2025-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_itempedido_cor_itempedido_cor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.FloatField(default=0),
        ),
    ]
